# Generated by Django 2.0.2 on 2018-03-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_ID', models.CharField(max_length=200)),
                ('Last_cleaned', models.DateTimeField(verbose_name='date published')),
                ('Status', models.IntegerField(verbose_name='Available space in bin, 1-10')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('Idd', models.CharField(max_length=200)),
                ('Ph_no', models.IntegerField(default=0)),
                ('ratings', models.IntegerField(default=0)),
                ('Binn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbin.Bin')),
            ],
        ),
    ]
